### ISSUE TITLE
Was 2.0.14 published out-of-tree? (Release appears missing in source on GitHub)

### ISSUE THREAD

**Issue by adamvoss** [Microsoft/vscode-json-languageservice#10]
@aeschli I see you published a version **2.0.14** to `npm`.  The `package.json` in this repository appears shows **2.0.13** and (to my knowledge) that would need to change to publish a different version to `npm`.

Will the source for 2.0.14 be released?

**Comment by aeschli** [comment]
@adamvoss Sorry, forgot to push. Fixed that.

**Comment by adamvoss** [comment]
Would there be any interest in an automatic deployment solution using Git tags?  This would ensure the source for releases is always published.

I use Travis CI to accomplish this on a number of projects, not sure is MS has a different provider that they would be more likely to use.
