### ISSUE TITLE
Consider using the official test suite?

### ISSUE THREAD

**Issue by Relequestual** [microsoft/vscode-json-languageservice#102]
Hello!

Given the importance of this module when using JSON Schema, I wonder, why not use the official test suite?

I did read you don't want external dependencies. Currently we do not offer a maintained version of the test suite as an npm release. We usually suggest people use git submodules to capture the tests they need.

I do see you have tests beyond validation. The official test suite currently only covers validation.

If it's difficult to justify time to do this, I may be able to help you find some additional justification.
Making the change is beyond the time I can offer currently.

**Comment by Trias** [comment]
(not the maintainer) As far as i know the module isn't in full compliance with the test suite yet. [This issue](https://github.com/microsoft/vscode-json-languageservice/issues/55) seems to be the most prominent which would fail many tests of the official test suite.

**Comment by Relequestual** [comment]
Thanks for linking @Trias !

The [Backlog](https://github.com/microsoft/vscode-json-languageservice/milestone/4) is quite small, so we can hope!

**Comment by Relequestual** [comment]
> Can you point me to the official test suite?

You can find it here: https://github.com/json-schema-org/JSON-Schema-Test-Suite
Apologies for the long delay!
