### ISSUE TITLE
Question about a minor test case with $refs

### ISSUE THREAD

**Issue by mati-o** [microsoft/vscode-json-languageservice#108]
In the following test case (`$refs in $ref - circular`) there are `$ref`s that are defined as follows:

https://github.com/microsoft/vscode-json-languageservice/blob/971dc54088278f521afacebe05ee8d92b76e39af/src/test/schema.test.ts#L890-L900

They are typed like `#definitions/hop1` rather than `#/definitions/hop1` - missing a `/` after the `#`. As far as I understand JSON Pointers, it should have been the latter. I am concerned of this because I'm trying to implement #55 and the aforementioned test case fails unless I include very ugly workarounds - I'd be happy to fix the test case by inserting the missing `/` wherever needed, unless there was a specific reason for writing them this way. 

Let me know if you want a PR

**Comment by KapitanOczywisty** [comment]
Correct. This might be breaking change though, so @aeschli could have some objections.

**Comment by aeschli** [comment]
That was a mistake in the test. Feel free to add the slash after the `#`!

**Comment by aeschli** [comment]
Fixed by d5ce22374d00c2dadb89dbff1230a05df60045ec
