### ISSUE TITLE
provide support for propertyOrder 

### ISSUE THREAD

**Issue by harrylepotter-win** [microsoft/vscode-json-languageservice#109]
propertyOrder is a feature of the draft-07 jsonschema spec. It would be incredibly useful to have this for vscode as it can act as a UI directive that makes creating complex json files from scratch with autocomplete much more intuitive for a user.

**Comment by aeschli** [comment]
I don't see `propertyOrder` any of the newer specs.
I see the discussions in https://github.com/json-schema/json-schema/issues/119 but seems to be out of scope for the JSON schema spec.

If you have more information, please add a pointer.
