### ISSUE TITLE
npm package still has engines.npm >= 7.0.0 and install fails.

### ISSUE THREAD

**Issue by wilsoncd35** [microsoft/vscode-json-languageservice#112]
I see in #99 where the `package.json` `engines.npm` property was removed from branch main. Tag v4.1.9 and the resulting npm package `vscode-json-languageservice@4.1.9` still include the `engines.npm` property. Installation via npm6 continues to fail.

I am specifically using `eslint-plugin-json` which has a dependency on this project package.

```
➜ npm i --save-dev eslint-plugin-json
...

➜ npm view vscode-json-languageservice engines
{ npm: '>=7.0.0' }
➜ npm view vscode-json-languageservice version
4.1.9

➜ grep 'version' node_modules/vscode-json-languageservice/package.json
  "version": "4.1.9",

➜ grep '"npm"' node_modules/vscode-json-languageservice/package.json
    "npm": ">=7.0.0"
```

**Comment by aeschli** [comment]
4.1.10 has the change.
