### ISSUE TITLE
Permit trailing commas depending on configuration

### ISSUE THREAD

**Issue by TonalidadeHidrica** [microsoft/vscode-json-languageservice#115]
It would be nice if we could we have a configuration to allow trailing commas without warnings.

The idea was originally posted in neoclide/coc-json#42 by @lanza .

**Comment by aeschli** [comment]
You can set `DocumentLanguageSettings.trailingCommas` to `ignore`.

Or set `allowTrailingCommas` in the schema.

**Comment by aeschli** [comment]
Please speak up if this is not good enough.
