### ISSUE TITLE
Language server seems to ignore client's TextDocumentClientCapabilities

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode-json-languageservice#12]
In the [jsonCompletion.ts](https://github.com/Microsoft/vscode-json-languageservice/blob/bb6c48e833895d49f8174e4884356ba560b6dc60/src/services/jsonCompletion.ts) file, all the `CompletionItem` instances are being created with `insertTextFormat` set to `InsertTextFormat.Snippet`.

Shouldn't it be checking the [initialization parameters](https://github.com/Microsoft/language-server-protocol/blob/e1ecd6a23a80735a1a7dc2abe3b684a7032e651e/protocol.md#initialize) of the client and seeing if the provided `ClientCapabilities` object's `textDocument.completion.completionItem.snippetSupport` property is set to `true` or `false`?

**Comment by rcjsuen** [comment]
Looks like this a [hard requirement](https://github.com/Microsoft/vscode/commit/c0b1937b47e28efd0dbe0fc886051227c86e515b) in the language server. If the client doesn't support snippets, then the JSON language server won't provide completion items. This is a shame as it forces the hand of the client to implement snippet support.

**Comment by aeschli** [comment]
Yes, the completions depend on the snippet support. It would be quite some work (and maintenance) to support both.

**Comment by aeschli** [comment]
We now pass the client capabilities to the service and could implement the request.
Not sure if there's still a demand for a service that doesn't not use snippets. PRs are welcome.

**Comment by aeschli** [comment]
If someone wants to adds support for text-only proposals, I'm open to it, but there are no plans from my side. I'm closing the issue.
