### ISSUE TITLE
`vscode-json-languageservice` on npmjs with wrong latest version

### ISSUE THREAD

**Issue by fannheyward** [microsoft/vscode-json-languageservice#120]
https://www.npmjs.com/package/vscode-json-languageservice shows the latest version is 4.1.0, it's wrong. We already has newer version 4.1.10, please correct the npmjs latest version tag.

The 4.1.0 version couldn't work with dot files. When we install `vscode-json-languageserver` with npm, will install the 4.1.0 vscode-json-languageservice.

**Comment by aeschli** [comment]
Sorry for that. 
I updated the latest tag to 4.1.10
