### ISSUE TITLE
validation works in vscode, but not directly through this project

### ISSUE THREAD

**Issue by DumpySquare** [microsoft/vscode-json-languageservice#125]
Greetings,

I'm working on a tool to programmatically validate json with a defined schema.  Some of the schemas have interesting references which vscode is the only public tool able to successfully validate.

I've tried to setup this project to be able to validate declarations outside of the vscode editor.  Some of them work and some don't.

Can anyone provide any insights to what might be going on?

This is the project:  https://github.com/DumpySquare/f5-declaration-validator

This is the test showing the examples:  https://github.com/DumpySquare/f5-declaration-validator/blob/main/tests/vscode_schemaVaildator.unit.tests.ts

example declarations:  https://github.com/DumpySquare/f5-declaration-validator/blob/main/src/models/examples.ts
schema: https://github.com/DumpySquare/f5-declaration-validator/blob/main/src/schemas/doSchema.json 

here is a screenshot of the results:
![image](https://user-images.githubusercontent.com/3260966/153411324-adf00a2d-5a25-40de-90fd-ef61a349ee09.png)

schema validation works in the UI:
![image](https://user-images.githubusercontent.com/3260966/153411678-4ac1d654-343a-4590-b7a9-8fa8cfc5b63a.png)

**Comment by aeschli** [comment]
Sorry, unfortunately I don't have the time to dig deeper here. 
Given that this works in VS Code it looks like this is not an issue with the JSON language service but the way the tests set up the service.
