### ISSUE TITLE
Augment schema for well known file type (e.g. package.json)

### ISSUE THREAD

**Issue by rictic** [microsoft/vscode-json-languageservice#131]
A variety of tools add their own configuration to Node's package.json files, generally under their own top level key. 

Is it possible to give vscode-json-languageservice the schema for these keys without otherwise interfering with its handling of the rest of a package.json file?

e.g. via a vscode extension or a $schema key like:

```json
{
  "name": "some-package",
  "version", "1.0.0",
  
  
  "some-tool": {
    "foo": "various keys and values to configure the some-tool command",
    "$schema": "https://example.com/some-tool.schema.json"
  }
}
```

**Comment by aeschli** [comment]
Augmenting works by associating multiple schemas to the same file pattern (in this case `**/package,json`). When the schema service looks for the applicable schemas for a given document, it takes all schemas that match and combines them with `allOf`.

You can see that in VS Code when you look at the schemas used for `package.json`
Open a package.json in the editor
Click on the `{} JSON` language indicator, in the hover click on 'Show Schemas'
You can see that are many schemas active, the main one for package.json and many others just describing extra properties.

**Comment by rictic** [comment]
Ah, yeah, I forgot to update this bug! We solved this for wireit by setting contributes.jsonValidation in our vscode extension's package.json: https://github.com/google/wireit/blob/0db070cdd80cfff7293c2bd980a28d86911212d5/vscode-extension/built/package.json#L7-L15

[The schema](https://github.com/google/wireit/blob/0db070cdd80cfff7293c2bd980a28d86911212d5/schema.json) is merged in with the package.json schema, so the json schema only needs to define the `"some-tool"` property.
