### ISSUE TITLE
Update to JSON schema draft 6

### ISSUE THREAD

**Issue by domoritz** [Microsoft/vscode-json-languageservice#15]
It would be awesome if the JSON language service could be updated to support a newer draft of JSON schema. 

See https://github.com/YousefED/typescript-json-schema/issues/156#issuecomment-366561041

Json-schema.org will soon be moving projects that do not support at least draft-06 to an "obsolete" or "older" implementations page. The main implementations page will promote implementations of draft06, draft-07, and future drafts.

**Comment by aeschli** [comment]
vscode-json-languageservice supports draft-06 since a while, support for draft-07 is planed.
