### ISSUE TITLE
[5.1.2 regression] exception when being bundled

### ISSUE THREAD

**Issue by AviVahl** [microsoft/vscode-json-languageservice#160]
After being bundled, `vscode-json-languageservice@5.1.2` throws an exception during evaluation:

```
Uncaught TypeError: _vscode_l10n__WEBPACK_IMPORTED_MODULE_4__.t is not a function
    <anonymous> webpack://vscodejsontest/./node_modules/vscode-json-languageservice/lib/esm/parser/jsonParser.js?:37
    js http://localhost:3000/dist/main.js:99
    __webpack_require__ http://localhost:3000/dist/main.js:303
    <anonymous> webpack://vscodejsontest/./node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js?:5
    js http://localhost:3000/dist/main.js:119
    __webpack_require__ http://localhost:3000/dist/main.js:303
    <anonymous> webpack://vscodejsontest/./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js?:44
    js http://localhost:3000/dist/main.js:79
    __webpack_require__ http://localhost:3000/dist/main.js:303
    <anonymous> webpack://vscodejsontest/./src/index.js?:44
    js http://localhost:3000/dist/main.js:279
    __webpack_require__ http://localhost:3000/dist/main.js:303
    <anonymous> http://localhost:3000/dist/main.js:355
    <anonymous> http://localhost:3000/dist/main.js:357
```

Steps to reproduce:
```
mkdir vscodejsontest
cd vscodejsontest
npm init -y
npm i vscode-json-languageservice webpack webpack-cli
mkdir src
echo "export * from 'vscode-json-languageservice';" > src/index.js
echo "<html><head><script src=\"dist/main.js\"></script></head><body></body></html>" > index.html
npx webpack --mode development
npx serve
```
(then open `http://localhost:3000` in browser and see exception)

@aeschli I believe it's related to `@vscode/i10n` changes in #159. browser build of that package might be broken.

**Comment by aeschli** [comment]
I set the latest release of vscode-json-languageservice back to 5.1.1 until we have fixed that issue

**Comment by AviVahl** [comment]
This got fixed. ty 👍

**Comment by timscharfenort8989** [comment]
> After being bundled, `vscode-json-languageservice@5.1.2` throws an exception during evaluation:
> 
> ```
> Uncaught TypeError: _vscode_l10n__WEBPACK_IMPORTED_MODULE_4__.t is not a function
>     <anonymous> webpack://vscodejsontest/./node_modules/vscode-json-languageservice/lib/esm/parser/jsonParser.js?:37
>     js http://localhost:3000/dist/main.js:99
>     __webpack_require__ http://localhost:3000/dist/main.js:303
>     <anonymous> webpack://vscodejsontest/./node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js?:5
>     js http://localhost:3000/dist/main.js:119
>     __webpack_require__ http://localhost:3000/dist/main.js:303
>     <anonymous> webpack://vscodejsontest/./node_modules/vscode-json-languageservice/lib/esm/jsonLanguageService.js?:44
>     js http://localhost:3000/dist/main.js:79
>     __webpack_require__ http://localhost:3000/dist/main.js:303
>     <anonymous> webpack://vscodejsontest/./src/index.js?:44
>     js http://localhost:3000/dist/main.js:279
>     __webpack_require__ http://localhost:3000/dist/main.js:303
>     <anonymous> http://localhost:3000/dist/main.js:355
>     <anonymous> http://localhost:3000/dist/main.js:357
> ```
> 
> Steps to reproduce:
> 
> ```
> mkdir vscodejsontest
> cd vscodejsontest
> npm init -y
> npm i vscode-json-languageservice webpack webpack-cli
> mkdir src
> echo "export * from 'vscode-json-languageservice';" > src/index.js
> echo "<html><head><script src=\"dist/main.js\"></script></head><body></body></html>" > index.html
> npx webpack --mode development
> npx serve
> ```
> 
> (then open `http://localhost:3000` in browser and see exception)
> 
> @aeschli I believe it's related to `@vscode/i10n` changes in #159. browser build of that package might be broken.

Gut
