### ISSUE TITLE
defaultSnippets not showing following v5.3.0

### ISSUE THREAD

**Issue by panoply** [microsoft/vscode-json-languageservice#191]
Recently updated from v5.3.0 to v.5.3.4 and `defaultSnippets` are no longer triggering correctly. The issue occurs specifically within array items. Take the following:

### Version **5.3.0**

In this version, default snippets will behave as intended. Invoking with `ctrl + space` available snippets will be shown in the array.

https://user-images.githubusercontent.com/7041324/236091206-8ca0c977-e2ad-4bab-b372-a673679774ee.mov

### Version **5.3.4**

In this version, default snippets will not be shown in the array. However, default snippets will show following the colon of the array list, which is not the intended behaviour.

https://user-images.githubusercontent.com/7041324/236091321-d75ca593-05d6-40ff-89b8-cb0ab0f82833.mov

Looking over recent commits, it seems to point to work done before the minor (v5.3.1) but have not tested on this version. Can confirm the issues occurs in vscode itself too, but unsure if known about and given the major activity in that repo thought it would be better to submit directly here. 

**Schema**

The schema store specification is quite large wherein the issue occurs. You can find it here if it helps: https://gist.github.com/panoply/a632c8914347ba9023f8374a60f2193f
 

Thanks for your continued efforts and work in this nexus.

**Comment by aeschli** [comment]
5.3.5 has a fix in that area. Can you try?
If you still see it, can you a sample code along with the schema?

**Comment by aeschli** [comment]
Testing with latest insiders:
![image](https://github.com/microsoft/vscode-json-languageservice/assets/6461412/d3a07181-7565-4919-a7fd-ddd176e7fa6b)
