### ISSUE TITLE
Intellisense recommends invalid schema uris for JSON Schema drafts

### ISSUE THREAD

**Issue by jeremyfiel** [microsoft/vscode-json-languageservice#194]
Type: Bug

When I type `$schema` in a json file, intellisense recommends JSON Schema draft versions in a list which includes draft-04 and draft-07 with an invalid uri per the specification.

per @Relequestual

>The correct URI for JSON Schema draft-04 or draft-07 is including the hash, per https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-5
>After draft-07, the hash was removed, so for 2019-09 and above, the uri should not include a trailing hash.
>In theory, if the URI isn't EXACTLY including the hash as defined in draft-07 or earlier, then the implementation does not know how it should process the schema.

**Comment by OR13** [comment]
+1

**Comment by benjagm** [comment]
+1
