### ISSUE TITLE
Sourcemaps broken in VSCode debugger

### ISSUE THREAD

**Issue by Hirse** [Microsoft/vscode-json-languageservice#2]
When I run the Tests in the VSCode debugger, any breakpoints in the TypeScript sources are disabled with the 

> Breakpoint ignored because generated code not found (source map problem?)

message.

**Comment by aeschli** [comment]
This got fixed by https://github.com/Microsoft/vscode-json-languageservice/commit/13f1d3b9f1ee85668c30bacf69d00d94648bd79a

**Comment by Hirse** [comment]
Looks like the bug in gulp-tsb got fixed and you can revert your workaround. 😉
