### ISSUE TITLE
Implementation of codeaction and executeCommand

### ISSUE THREAD

**Issue by adamYzamri** [microsoft/vscode-json-languageservice#20]
Hi,
I want to implement codeaction and execute command in certain cases.
Can I  add a pull request that extends the jsonworker interface to support this, to be added in the contributions parameter in the constructor?
Thanks

**Comment by aeschli** [comment]
That would be great.
You'd start by adding `doCodeActions` to 
https://github.com/Microsoft/vscode-json-languageservice/blob/master/src/jsonLanguageService.ts
After that we can update monaco-json and the connect the monaco API to the worker

**Comment by adamYzamri** [comment]
Hi,
If I want to use a specific implementation for a json code action, what is the correct way to configure it if I am using the vscode repository. Do I have to copy the code and pass the contribution in the json-lang service constructor?

**Comment by aeschli** [comment]
@adamYzamri Not sure I understand the question. If the question is how to run VSCode with the vscode-json-languageservice from source (not npm), see here: https://github.com/microsoft/vscode-json-languageservice#how-can-i-run-and-debug-the-service-inside-an-instance-of-vscode

I'm closing this issue as there are currently no plans to add code actions. I'm still open to PRs.
