### ISSUE TITLE
Support fetching schemas from github URLs

### ISSUE THREAD

**Issue by rickardp** [microsoft/vscode-json-languageservice#225]
Support fetching schemas from URLs like `https://github.com/MyOrg/my-repo/blob/master/schemas/some-schema.json`.

Currently this is not possible. There is raw.githubusercontent.com but this does not work with private repositories.

By allowing special handling for GitHub URLs (using the saved credentials), it would be possible to seamlessly reference schemas in private repos on GitHub

**Comment by aeschli** [comment]
The vscode-json-languageservice doesn't do the fetching of schemas itself, but uses the provided `SchemaRequestService` to do that.
Your request would be implemented in the provided `SchemaRequestService`
Maybe you were thinking of having such functionality in VS Code itself. It would have to be filed there.
e

**Comment by rickardp** [comment]
Makes sense. I wasn't able to decipher from package.json where the schemas are loaded. Could you please help me out with which repo that would be?
