### ISSUE TITLE
[Feature Request] Json Schema show schema details. in CompletionItemLabel

### ISSUE THREAD

**Issue by honhimW** [microsoft/vscode-json-languageservice#235]
As far as I know, the current [JSON worker](https://github.com/microsoft/vscode-json-languageservice/blob/main/src/services/jsonCompletion.ts) uses the `string` for the label property when handling completion items, rather than the `CompletionItemLabel` interface. Consequently, it cannot display inline brief hints in the suggestions. What I intend to convey is that I hope there could be a configuration option to control this behavior, allowing support for setting corresponding details on JSON schemas.
```typescript
export interface CompletionItem {
    label: string | CompletionItemLabel;
    // ...
}

export interface CompletionItemLabel {
    label: string;
    detail?: string;
    description?: string;
}
```
However, I would like to set the information in CompletionItemLabel#description or #detail to display it in the suggestions.
Because most of the time, I don’t want or need to hover over the document for this.

Sincerely looking for you reply.

**Comment by sumimakito** [comment]
Hello @honhimW, it's true that this useful feature is missing. I have opened a pull request to implement it.

**Comment by honhimW** [comment]
@sumimakito 
Wow, that's great news! Thank you so much for your work.❤️
