### ISSUE TITLE
Incorrect handling of "allOf' (intersection types)

### ISSUE THREAD

**Issue by jcayzac** [microsoft/vscode-json-languageservice#245]
When a JSON schema contains intersection types (`allOf`), the service outputs `property not allowed` validation errors for a valid JSON document.

See minimal repro [here](https://github.com/jcayzac/repro-vscode-json-schema-bug).

**Comment by jcayzac** [comment]
I think the code here is wrong:

https://github.com/microsoft/vscode-json-languageservice/blob/main/src/parser/jsonParser.ts#L431-L439

If you validate the node against each sub-schema, then of course all its properties not allowed by the current sub-schema will create validation errors. Once all the errors are merged, all of the properties in fact allowed by the schema will end up marked as "not allowed".

**Comment by jcayzac** [comment]
@aeschli Is this the wrong way to raise issues for this project, maybe? I see no triage, reaction or label has happened since I opened it.

**Comment by aeschli** [comment]
Hi @jcayzac, apologies, I was on vacation the last two weeks.

'additionalProperties' and 'allOf' don't work well together. Therefore `unevaluatedProperties` got introduced in schema draft 2011-09.

See https://json-schema.org/understanding-json-schema/reference/object#extending

Contributions are welcome. For PRs you will have to agree to a https://github.com/microsoft/vscode/wiki/Contributor-License-Agreement

**Comment by jcayzac** [comment]
@aeschli are you saying the input schema is invalid?

**Comment by aeschli** [comment]
Is is valid, but doesn't mean what you are expecting. The link https://json-schema.org/understanding-json-schema/reference/object#extending explains it in detail.
