### ISSUE TITLE
Creating .d.ts file for json parser

### ISSUE THREAD

**Issue by JPinkney** [Microsoft/vscode-json-languageservice#38]
Hi, 

we are currently using a forked version of the json parser in the [YAML Language Server](https://github.com/redhat-developer/yaml-language-server) and we were wondering if we could create a .d.ts file for the json parser so that we can extend specific parts of it rather than having to fork it.

**Comment by aeschli** [comment]
The new API `newJSONDocument` & type definitions for ASTNode lets you replace our parser with yours.

Please give it a try, if there's anything I can add let me know.

**Comment by JPinkney** [comment]
Alright, thanks for letting me know! I'll check it out!
