### ISSUE TITLE
any plans for creating a server that takes requests via stdin?

### ISSUE THREAD

**Issue by prabirshrestha** [Microsoft/vscode-json-languageservice#4]
I would like to use this language server in vim https://github.com/tjdevries/nvim-langserver-shim and would like to make the configuration as simple as

```sh
npm i -g vscode-json-languageservice
```

```viml
let g:langserver_executables = {
      \ 'css': {
        \ 'name': 'vscode-json-languageservice',
        \ 'cmd': ['vscode-css-languageservice')],
        \ },
      \ }
```

**Comment by aeschli** [comment]
This node is not implementing a language server, it's just a library that can be used in any context.
We have a json language server in vscode that we could publish as a node_module.
Please file the request there.

**Comment by danr** [comment]
> Please file the request _there_.

Where is _there_?

Context:
This repo is listed at https://microsoft.github.io/language-server-protocol/implementors/servers/ which gave me the impression that this was a language server implementation.

**Comment by DeltaEvo** [comment]
If you want a binary version for it, you have one in the vscode repo

To be used by everyone I have extracted them
https://github.com/vscode-langservers/vscode-json-languageserver-bin and
published it on npmjs.com

 (PS: I need to update it and write some doc for the json-language-server,
I will try to do it quickly)

**Comment by danr** [comment]
@DeltaEvo : thank you! Do you know how to update the list on https://microsoft.github.io/language-server-protocol/implementors/servers/ ?

**Comment by egamma** [comment]
@danr it is described at the top of the page

![image](https://user-images.githubusercontent.com/172399/37024921-945156a2-212a-11e8-8ceb-240168c06638.png)

**Comment by danr** [comment]
@egamma: thanks, made a PR

**Comment by rcjsuen** [comment]
Does it even make sense to list this repository on the LSP page if it's not actually a language server?

**Comment by danr** [comment]
@rcjsuen: I don't think it does
