### ISSUE TITLE
custom keywords

### ISSUE THREAD

**Issue by Allam76** [microsoft/vscode-json-languageservice#41]
In the case of dynamic content, I'm wondering if custom keywords like [ajv](https://ajv.js.org/custom.html#define-keyword-with-validation-function) could be possible.

In that case, I guess a user setting for the functions as well as the target schema would be needed.

Another option is to extend the `$ref` with hyper schema like syntax:
```json
"properties":{
    "type":{"type": "string"},
    "name":{
      "$ref":{
        "hrel":"http://my-host/dynamicType/{type}",
        "templatePointers":{
             "type": "/type"
        }
   }
  }
}
```
and input:
```json
{"type": "user", "name": "Peter"}
```
with return something like this:
```json
{
  "type": "string",
  "enum":["John","Peter"]
}
```
In both cases we move slightly away from json schema standard...

Let me know if this makes sense.

**Comment by Allam76** [comment]
Made an implementation of variant 2 in [fork:](https://github.com/Allam76/vscode-json-languageservice). All tests pass. Also added tests for service, completion and validation.

Please check if make sense for PR.

**Comment by aeschli** [comment]
We don't want to fork off JSON schema and come up with our own schema flavor.

To support dynamic value sets the current story is to either
- implement your own completion & validation providers (as we do e.g. for package.json dependency completion in the npm extension: https://github.com/microsoft/vscode/blob/master/extensions/npm/src/features/packageJSONContribution.ts
- provide schemas from a text document provider as we do for our settings schemas.
(define your own text document provider and let it serve JSON schemas)
