### ISSUE TITLE
JSON 5 support

### ISSUE THREAD

**Issue by acao** [microsoft/vscode-json-languageservice#42]
is it possible that monaco will support a json5 mode anytime soon? `json5` is being used widely in many ecosystems, so it would be handy! https://github.com/json5/json5-vscode is in progress. Doesn't look like there is any language server implementation for JSON5 yet, hmmm...

**Comment by aeschli** [comment]
+1 for more JSON5 support but not sure it should be part of this service. Ideally done in it's own service, referencing this service for schemas and features.

**Comment by DaHaiz** [comment]
+1 would be awesome to see JSON5 support land in Monaco

**Comment by aeschli** [comment]
Out of scope for this service. Should be done in it's own node_module, referencing this service for schemas and features.

**Comment by acao** [comment]
just as a point of reference for anyone who wants to go down this path - @aeschli do you know anything about the MS aligned `jsonc` language ID? At one point @orta referred to it if i recall. Is that just built into `vscode`? that would be a cool starting point to extract something if ones need is just to support comments in json. json5 is obviously very different as it accept the entire object literal syntax, but `jsonc` i think would satisfy many needs

**Comment by aeschli** [comment]
Yes, the built-in JSON language support provides two language modes:  JSON and 'JSON with comments'. They are both implemented by the parser provided by the vscode-json-languageservice. Yes, this could be taken as starting point, but there  also already existing JSON5 parsers out there.
