### ISSUE TITLE
Allow exclusive globs in `fileMatch`

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/vscode-json-languageservice#46]
I&nbsp;would expect&nbsp;that:
```jsonc
"json.schemas": [
	{
		"fileMatch": [
			"/foo/*.json",
			"!/foo/*.excluded.json"
		],
		"url": "/foo.schema.json"
	}
]
```
would&nbsp;not&nbsp;add the&nbsp;`foo.schema.json` to&nbsp;any&nbsp;files ending&nbsp;with&nbsp;`.excluded.json`.

**Comment by aeschli** [comment]
Good suggestion. If anyone wants to make a PR, I'm happy to take it.

**Comment by aeschli** [comment]
To verify: 
- add to the settings:
```
	"json.schemas": [
		{
			"fileMatch": [
				"/foo/*.json",
				"!/foo/*.excluded.json"
			],
			"url": "http://json.schemastore.org/package"
		}
	]
```
- create a folder `foo` with some JSON files in e.g. `bar.json`, `bar.excluded.json`
- verify that you get package.json code completions in `bar.json` but not in `bar.excluded.json`
