### ISSUE TITLE
incomplete declarations in @3.5.2?

### ISSUE THREAD

**Issue by acao** [microsoft/vscode-json-languageservice#51]
I feel like this image sums it all up:

![image](https://user-images.githubusercontent.com/1368727/78610714-72a06180-7833-11ea-8306-22aa5a714934.png)

Any chance it's something wrong I am doing? normal yarn install

**Comment by aeschli** [comment]
I don't see any issues also I'm not aware of any changes
- new npm project
- yarn add vscode-json-languageservice -S
- I see all files
![image](https://user-images.githubusercontent.com/6461412/78648459-4b41a700-78bc-11ea-9c37-cd06d0aba5e0.png)

BTW you are not supposed to import `lib/esm/parser/jsonParser`. That's considered internal and can change any time.
The official API is what you get when you import `vscode-json-languageservice`

**Comment by acao** [comment]
@aeschli thanks, this makes much more sense to me! i ended up using `jsonLanguageService.parseJSONDocument()` for my custom worker and it worked out just fine. Thanks!
