### ISSUE TITLE
$ref should accept $id references

### ISSUE THREAD

**Issue by ImBoop** [microsoft/vscode-json-languageservice#55]
As part of JSONSchema Draft 6, $ref can point to a definition defined with an `$id` (or just `id`, spec seems vague if its `$id` or `id` in v6) -- it would be wonderful if we could get support for that here.

For instance, in definitions we will be able to use `{"references": { "$id": "#test", ... }}` and in our core properties, refer to it via `{"properties": {"$ref": "#test", ...}}`

Thanks!

**Comment by forivall** [comment]
I'm _interested_ in tackling this, either in a PR or in an external vscode extension (probably both, as i'll want to have the flexibility of my own extension for other resolver logic for [external references](https://tools.ietf.org/html/draft-wright-json-schema-01#section-9.2.2), and then i'll upstream relevant features).

_some links:_
* [json-schema.org Documentation](https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref)
* [draft 6 spec on $id](https://tools.ietf.org/html/draft-wright-json-schema-01#section-9.2)

**Comment by aeschli** [comment]
Hi @forivall, thanks for the interest, you are very welcome, a PR would be great! 

We currently resolve the $refs in a step called `resolveSchemaContent`: https://github.com/microsoft/vscode-json-languageservice/blob/65f660bb0db367a4df4141d07dabb2f1fc71d9d5/src/services/jsonSchemaService.ts#L392

To run and debug this, see [here for instructions](https://github.com/microsoft/vscode-json-languageservice/blob/main/README.md#how-can-i-run-and-debug-the-service). You can find some ref related tests [her](https://github.com/microsoft/vscode-json-languageservice/blob/65f660bb0db367a4df4141d07dabb2f1fc71d9d5/src/test/schema.test.ts#L68).

I'm happy to help. I've started looking into it but realized it's not a trivial change and we might have to restructure the way we do the resolving.

**Comment by jviotti** [comment]
As a workaround, my [JSON Schema CLI tool](https://github.com/intelligence-ai/jsonschema) supports performing bundling without making use of identifiers to at least make schemas work with Visual Studio Code: https://github.com/Intelligence-AI/jsonschema/blob/main/docs/bundle.markdown.
