### ISSUE TITLE
DocumentSymbol pop-up

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-json-languageservice#56]
In my sample workspace, I often see this. Settings, launch files etc are all normal sized

<img width="717" alt="Screenshot 2020-04-17 at 13 46 50" src="https://user-images.githubusercontent.com/1794099/79568588-67142c80-80b6-11ea-9f72-e3006eb87817.png">

**Comment by aeschli** [comment]
The file name `launch` and `user` are interesting. Looks like this comes from  (virtual) settings schema document. Is it always these documents?
If you turn on `json.trace.server` and open the `output > JSON ..` tab you can see the full request URIs.

**Comment by aeschli** [comment]
In VSCode we generate schemas and keep them in virtual documents with URIs such as:
- `vscode://schemas/settings/user"` for the user settings schema
- `"vscode://schemas/launch"` for the launch config schema

They can by lartge, if you have a lot of extension with setting and launch config contributions.

But, these schema are not opened in editors, they are just virtual documents. No folding or document symbol request should be made on these.

@jrieken Do you still these dialogs and if yes, can you track down where the document symbol request come from?

**Comment by jrieken** [comment]
nope, haven't seen it since a while

**Comment by aeschli** [comment]
Closing the issue then. Please reopen if you see it again.
