### ISSUE TITLE
Question: how to leverage JSON validation and syntax highlight

### ISSUE THREAD

**Issue by eriolchan** [microsoft/vscode-json-languageservice#59]
Hi, I am writing an VSCode extension for a definition language which is based on JSON format, add some grammar and the file extension is still *.json. Once I create a new language id for this new language, the existing JSON syntax highlight and basic validation disappears. Is there any way to leverage JSON syntax highlight, bracket auto-close and JSON format validation in my VSCode extension? Is there any document or example to follow?

**Comment by aeschli** [comment]
If you define your own language id, you basically have to duplicate the JSON basics extension (grammar, language configuration) and you have to provide your own language server. At least when you implement your server you can base it on the vscode-json-languageservice (which is what this repo is for).
Maybe explain why you realy need your own language id. What's special about your definition language?

**Comment by eriolchan** [comment]
@aeschli [here](https://github.com/microsoft/vscode-dtdl) is our VSCode extension. It provides language support for DTDL which is a definition language based on JSON format.

Recently there is a user case to support: 1) user create new file, 2) select language mode (dtdl), 3) and then author by DTDL intelliSense. In this case, we need to add a new language id to declare the file type on demand. The tricky thing is that DTDL is just an ordinary JSON file with DTDL context/syntax, so the file extension is still *.json.

In the next step, we will build our own language server to handle DTDL intelliSense. When you mentioned we can base on vscode-json-languageservice, do you mean we can copy the code of (syntax highlight, bracket auto-close and JSON format validation) to our LS, or there is a library to leverage, or calling JSON language service? What's the best practice you recommend?

BTW, is tmLanuage.json able to provide the functions (syntax highlight, bracket auto-close and JSON format validation)?

**Comment by aeschli** [comment]
See https://code.visualstudio.com/api/language-extensions/overview for more oinformation on language support.
- tmLanuage.json is only for syntax highlighting
- language-configuration is for auto-close, comments and the like. 
- Validation, code complete, hovers come from [providers](https://code.visualstudio.com/api/language-extensions/programmatic-language-features) that are ideally forwarding to a [language server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide).
We have extracted all the JSON language smarts (validation, code complete, hovers) in the vscode-json-languageservice. It's a library that might be helpful as a base. There's another library [jsonc-parser](vscode-json-languageservice) that implements the scanner/parser.

Do yes, you basically have to copy and extend.

**Comment by aeschli** [comment]
I also want to say that if your language syntax is pure JSON, but with a specific properties and values, then you don't necessary need to define your own language but can just contribute additional providers to JSON. E.g. additional validation, hovers and code completion.
That way you don't have to redefine the full JSON support. Your providers will have to probe the file content or project information to figure out if it is DTDL file or not and only get active when it is.
The status bar would still show JSON. And you would use the regular JSON syntax highlighting and language configuration.

**Comment by eriolchan** [comment]
Thanks for your advice, @aeschli. Your last suggestion is our existing solution, I will take your opinion and re-prioritize the use case of new language id.
