### ISSUE TITLE
requestService is undefined in JSONWorker

### ISSUE THREAD

**Issue by apalsapure** [Microsoft/vscode-json-languageservice#6]
I'm trying to create two editors on same page, which uses schema validation. I have set the schemas like

    monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
            validate: true,
            schemas: schemas
    });

Where `schemas` is an array of 

    {
        uri: 'http://server/foo.json',
        fileMatch: ['http://server/foo.json'],
        schema: {
        }
    }

Then I construct the editor by providing `model`

     var monacoModel = monaco.editor.getModel('http://server/foo.json');
      monacoModel = monacoModel || monaco.editor.createModel('{}', 'json', 'http://server/foo.json');

     var editor1 = monaco.editor.create(document.getElementById('editor-container-123'), {
                model: monacoModel,
                language: 'json',
    }

Now when I construct second editor for a different URI, `resetSchema` event is fired; which internally clears schema provided through `setDiagnosticsOptions` for the given URI. Now as there is no `unresolvedSchema` for current URI, it tries to download it by calling `loadSchema` function. In this function `this.requestService` is undefined and hence I get the error `No schema request service available`

I didn't find anything on how can I set `this.requestService`. I have found that there is an import done for `SchemaRequestService` in [jsonSchemaService.ts](https://github.com/Microsoft/vscode-json-languageservice/blob/master/src/services/jsonSchemaService.ts).

I tried to do this on playground, and it failed there also, with the same error.

If I delete following lines from `clearSchema`, everything **works fine**.

     this.resolvedSchema = null,
     this.unresolvedSchema = null

but don't know it's impact.

Thanks for the help.

**Comment by aeschli** [comment]
When you define the schema, why do give it the same id as the document you match it against?
```json
{
    uri: 'http://server/foo.json',   < ID of the schema
    fileMatch: ['http://server/foo.json'],   < pattern that schema matches against
    schema: {
    }
}
```

I suggest to use a different URI for the schema:
'schema://server/foo.json'
