### ISSUE TITLE
date-time validation

### ISSUE THREAD

**Issue by ubmarco** [microsoft/vscode-json-languageservice#64]
Hi,
I'm using the [coc.nvim](https://github.com/neoclide/coc.nvim) extension with [coc-json](https://github.com/neoclide/coc-json) to develop jsonschema files in neovim. I stumbled upon a problem with date-time validation.
This is my schema:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "date": {
      "type": "string",
      "format": "date-time"
    }
  }
}
```
This is my JSON:
```json
{
  "date": "020-12-23T18:25:43.511Z"
}
```
The year is missing the first digit and coc-json does not report any errors. Actually no errors are detected for the `date-time` string format, it seems the validation is completely ignored. When I set the `format` to `email`, all erroneous mail addresses are reported, so the format validation is basically working.
Here is how it should behave: https://www.jsonschemavalidator.net/s/AjNuDoH9
I first raised [this](https://github.com/neoclide/coc-json/issues/22) issue for coc-json, but I was redirected to this JSON language server.

Is that a known issue or am I doing something wrong?

**Comment by KapitanOczywisty** [comment]
They are using [old version (3.3.0)](https://github.com/neoclide/coc-json/blob/66b482dbc8008b9a111e6141aa2e63baa16fb2d4/package.json#L104) of this extension, but `date-time` format was added in 3.3.1.

In vscode: 
![image](https://user-images.githubusercontent.com/44417092/88304028-02491d80-cd08-11ea-8eee-cf34099dcffd.png)

**Comment by ubmarco** [comment]
Thanks a lot for the insight! I'll try to get the dependency updated.
