### ISSUE TITLE
Are the `filterText` and `label` accidentally swapped?

### ISSUE THREAD

**Issue by rwols** [microsoft/vscode-json-languageservice#82]
This server returns LSP completion items in the following format:

```
"word_wrap": $1
^^^^^^^^^^^ filterText
 ^^^^^^^^^ label
```

Shouldn't it be the other way around? I always assumed the `filterText` should ideally be a substring of the `label` (with some room for possible interesting exceptional completion items):

```
"word_wrap": $1
^^^^^^^^^^^ label
 ^^^^^^^^^ filterText
```

That is, the user presumably already typed the first double-quote, and the filterText should now start matching the word `word_wrap`.

**Comment by aeschli** [comment]
The filter text is matched against the content before the cursor that is replaced. That content is specified by the `range` of the completion item's `textEdit`. 
We always replace the full key or property, so the quotes are included in that range.
The label is what the user sees in the completion widget. There we chose to not show quotes for a cleaner look.
