### ISSUE TITLE
Deprecation in Validations

### ISSUE THREAD

**Issue by Trias** [microsoft/vscode-json-languageservice#87]
Looking at the code it does not seem to be that case that "deprecationMessage" or "deprecated: true" (new property in JSON Schema 2019-09) are supported in Diagnostics.

LSP supports this since version 3.15 as a "DiagnosticTag", see https://microsoft.github.io/language-server-protocol/specification#diagnostic

I would be interested in providing a pull request, just want to make sure in advance if you are interested and/or have any pointers.

**Comment by KapitanOczywisty** [comment]
AFIK 2019-09 is not supported at all, but feel free to make PR to add DiagnosticTag and/or `deprecated: true`. `deprecationMessage` is used by vscode itself in settings (example `"search.location": "panel"`), though I don't think that they would have problem with that change.

**Comment by andrewbranch** [comment]
Appears to be fixed by https://github.com/microsoft/vscode-json-languageservice/pull/133

**Comment by aeschli** [comment]
Thanks, correct, I forgot to close this issue
