### ISSUE TITLE
Parse $ref according to JSON pointer spec

### ISSUE THREAD

**Issue by praneetloke** [microsoft/vscode-json-languageservice#91]
I wasn't too sure if this is a valid scenario for the language service to support but the schema I am working with uses type definitions that contain flattened hierarchies. Is this something that the language service could support or should I spread the type definition path into objects before providing configuring the service with the type definitions?

**Does not work**

```js
// Configures two JSON schemas, with references.

var jsonCode = [
    '{',
    '    "p1": "v3",',
    "}"
].join('\n');
var modelUri = monaco.Uri.parse("a://b/foo.json"); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, "json", modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [{
        uri: "http://myserver/foo-schema.json", // id of the first schema
        fileMatch: [modelUri.toString()], // associate with our model
        schema: {
            type: "object",
            properties: {
                p1: {
                    $ref: "#/types/q/custom"
                },
            },
            types: {
                "r/custom": {
                    type: "object",
                    properties: {
                        x: {
                            enum: ["v1"]
                        }
                    }
                },
                "q/custom": {
                    type: "object",
                    properties: {
                        y: {
                            enum: ["v2"]
                        }
                    }
                }
            }
        }
    }]
});

monaco.editor.create(document.getElementById("container"), {
    model: model
});
```

**Works**

```js
// Configures two JSON schemas, with references.

var jsonCode = [
    '{',
    '    "p1": "v3",',
    "}"
].join('\n');
var modelUri = monaco.Uri.parse("a://b/foo.json"); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, "json", modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [{
        uri: "http://myserver/foo-schema.json", // id of the first schema
        fileMatch: [modelUri.toString()], // associate with our model
        schema: {
            type: "object",
            properties: {
                p1: {
                    $ref: "#/types/q/custom"
                },
            },
            types: {
                "r": {
                    "custom": {
                        type: "object",
                        properties: {
                            y: {
                                enum: ["v2"]
                            }
                        }
                    }
                },
                "q": {
                    "custom": {
                        type: "object",
                        properties: {
                            y: {
                                enum: ["v2"]
                            }
                        }
                    }
                }
            }
        }
    }]
});

monaco.editor.create(document.getElementById("container"), {
    model: model
});
```

**Comment by KapitanOczywisty** [comment]
I'm afraid that this is against specification. Unfortunately also `$id` is not implemented here, which would give opportunity for something similar. However there is nothing stopping you from passing schema through recursive function first to replace "flat" keys with proper structure.

**Comment by praneetloke** [comment]
@KapitanOczywisty ah I was sort of hoping that wasn't the case.

> However there is nothing stopping you from passing schema through recursive function first to replace "flat" keys with proper structure.

Yeah I am thinking of building an alternate structure that groups types by their parent path segment from the original schema.

It sounds like this just isn't something that the language service would gain as a feature. Do you advise that I close this issue?

**Comment by KapitanOczywisty** [comment]
I was researching a bit about this after commenting and found out that by [JSON Pointer specification](https://tools.ietf.org/html/rfc6901#section-3) you should use `~1` to escape `/`, thus `$ref` becomes: `$ref: "#/types/q~1custom"`. That further proves that `/` in key should be treated as part of this key's name. You can see this in action here: https://www.jsonschemavalidator.net/s/pFv9tscX , but this isn't implemented in vscode at all.

Flat structures ain't gonna happen, but `~0` and `~1` escapes probably should be implemented. What do you think @aeschli ?

**Comment by aeschli** [comment]
@aeschli Good find, we should parsing the refs according to the JSON pointer spec.
