### ISSUE TITLE
Add support for passing regex flags

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode-json-languageservice#96]
The following works in [this](https://www.jsonschemavalidator.net/) online JSON schema validator:

```json
{
  "type": "string",
  "pattern": "(?i)^alt\\+C$"
}
```

But from Monaco I'm getting this error: `SyntaxError: Invalid regular expression: /(?i)^alt\+C$/: Invalid group.`

It looks like regex flags can't be passed at all with this library:

https://github.com/microsoft/vscode-json-languageservice/blob/07fec3faafa3f32915dcd6fcc6999a91ad113f88/src/parser/jsonParser.ts#L647-L648

IMHO this is something pretty necessary, one can't just compile away the "i" flag for example, the combinatorics would explode in some cases.

**Comment by KapitanOczywisty** [comment]
JSON Schema requires patterns to support ***at least*** ecma 262 (RegExp from JavaScript), thus this is technically correct implementation. For now you need to use `"^[Aa][Ll][Tt]\\+[Cc]$"`.

As for the future, using 3rd party library shouldn't be hard to do, not sure which one would be the best for node and browsers, at the same time also fully compatible with ecma 262. Probably the best bet would be to use [XRegExp](https://www.npmjs.com/package/xregexp), which compiles new features to the native RegExp object. @aeschli is this a good idea?

**Comment by aeschli** [comment]
Thanks for the research @KapitanOczywisty. 
If RegExp from JavaScript is good enough then I'd stick with that. 
From the top of my head, I'm not aware of more requests to support more powerful Regex flavors.

**Comment by KapitanOczywisty** [comment]
@aeschli Based on https://www.regular-expressions.info/javascript.html case insensitive modifier is the biggest thing which native RegExp is lacking. We could probably allow `(?i)` as an exception on the beginning of the pattern and replace with `new RegExp(schema.pattern.substr(4), 'i')`. This would satisfy most use cases without major overhead.

**Comment by aeschli** [comment]
Makes sense!

**Comment by fabiospampinato** [comment]
Thanks everyone for addressing this so quickly!
